In [2]:
#dot product

import numpy as np

Rows = int(input("Give the number of rows:"))  
Columns = int(input("Give the number of columns:"))  
   
mat1 = []  
print("Please give the entries of matrix1 row-wise:")  
  
# For user input  
for x in range(Rows):
    r = []  
    for y in range(Columns): 
        r.append(int(input()))  
    mat1.append(r)  


for x in range(Rows):  
    for y in range(Columns):  
        print(mat1[x][y], end=" ")  
    print()  


Rows= int(input("Give the number of rows:"))  
Columns= int(input("Give the number of columns:"))  
   
mat2 = []  
print("Please give the entries of matrix 2 row-wise:")  
  
# For user input  
for x in range(Rows):
    r = []  
    for y in range(Columns): 
        r.append(int(input()))  
    mat2.append(r)  


for x in range(Rows):  
    for y in range(Columns):  
        print(mat2[x][y], end=" ")  
    print()  


res = np.dot(mat1,mat2)
 
print("dot product \n",res)

Give the number of rows:2
Give the number of columns:2
Please give the entries of matrix1 row-wise:
2
1
0
3
2 1 
0 3 
Give the number of rows:2
Give the number of columns:2
Please give the entries of matrix 2 row-wise:
1
1
3
2
1 1 
3 2 
dot product 
 [[5 4]
 [9 6]]


In [5]:
#transpose

Rows = int(input("Give the number of rows:"))  
Columns = int(input("Give the number of columns:"))  
   
mat = []  
print("Please give the entries of matrix1 row-wise:")  
  
# For user input  
for x in range(Rows):
    r = []  
    for y in range(Columns): 
        r.append(int(input()))  
    mat.append(r)  


for x in range(Rows):  
    for y in range(Columns):  
        print(mat[x][y], end=" ")  
    print()  

              
result = np.transpose(mat)
    
print("transpose \n",result)

Give the number of rows:3
Give the number of columns:3
Please give the entries of matrix1 row-wise:
4
1
5
12
3
6
4
5
6
4 1 5 
12 3 6 
4 5 6 
transpose 
 [[ 4 12  4]
 [ 1  3  5]
 [ 5  6  6]]


In [7]:
#trace

Rows = int(input("Give the number of rows:"))  
Columns = int(input("Give the number of columns:"))  
   
mat = []  
print("Please give the entries of matrix1 row-wise:")  
  
# For user input  
for x in range(Rows):
    r = []  
    for y in range(Columns): 
        r.append(int(input()))  
    mat.append(r)  


for x in range(Rows):  
    for y in range(Columns):  
        print(mat[x][y], end=" ")  
    print()  

              
result = np.trace(mat)
    
print("trace \n ",result)

Give the number of rows:3
Give the number of columns:3
Please give the entries of matrix1 row-wise:
4
1
5
12
3
6
4
5
6
4 1 5 
12 3 6 
4 5 6 
trace 
  13


In [8]:
#rank

Rows = int(input("Give the number of rows:"))  
Columns = int(input("Give the number of columns:"))  
   
mat = []  
print("Please give the entries of matrix1 row-wise:")  
  
# For user input  
for x in range(Rows):
    r = []  
    for y in range(Columns): 
        r.append(int(input()))  
    mat.append(r)  


for x in range(Rows):  
    for y in range(Columns):  
        print(mat[x][y], end=" ")  
    print()  

              
result = np.linalg.matrix_rank(mat)
    
print("Rank of matrix \n" ,result)

Give the number of rows:3
Give the number of columns:3
Please give the entries of matrix1 row-wise:
4
1
5
12
3
6
4
5
6
4 1 5 
12 3 6 
4 5 6 
Rank of matrix 
 3


In [9]:
#determinant

Rows = int(input("Give the number of rows:"))  
Columns = int(input("Give the number of columns:"))  
   
mat = []  
print("Please give the entries of matrix1 row-wise:")  
  
# For user input  
for x in range(Rows):
    r = []  
    for y in range(Columns): 
        r.append(int(input()))  
    mat.append(r)  


for x in range(Rows):  
    for y in range(Columns):  
        print(mat[x][y], end=" ")  
    print()  

              
result = np.linalg.det(mat)
    
print("Determinant of matrix \n" ,result)

Give the number of rows:3
Give the number of columns:3
Please give the entries of matrix1 row-wise:
6
1
1
4
-2
5
2
8
7
6 1 1 
4 -2 5 
2 8 7 
Determinant of matrix 
 -306.0


In [10]:
#inverse

Rows = int(input("Give the number of rows:"))  
Columns = int(input("Give the number of columns:"))  
   
mat = []  
print("Please give the entries of matrix1 row-wise:")  
  
# For user input  
for x in range(Rows):
    r = []  
    for y in range(Columns): 
        r.append(int(input()))  
    mat.append(r)  


for x in range(Rows):  
    for y in range(Columns):  
        print(mat[x][y], end=" ")  
    print()  

              
result =np.linalg.inv(mat)
    
print("Inverse of matrix \n" ,result)

Give the number of rows:3
Give the number of columns:3
Please give the entries of matrix1 row-wise:
6
1
1
4
-2
5
2
8
7
6 1 1 
4 -2 5 
2 8 7 
Inverse of matrix 
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [11]:
#eigen values

Rows = int(input("Give the number of rows:"))  
Columns = int(input("Give the number of columns:"))  
   
mat1 = []  
print("Please give the entries of matrix1 row-wise:")  
  
# For user input  
for x in range(Rows):
    r = []  
    for y in range(Columns): 
        r.append(int(input()))  
    mat1.append(r)  


for x in range(Rows):  
    for y in range(Columns):  
        print(mat1[x][y], end=" ")  
    print()  


Rows= int(input("Give the number of rows:"))  
Columns= int(input("Give the number of columns:"))  
   
mat2 = []  
print("Please give the entries of matrix 2 row-wise:")  
  
# For user input  
for x in range(Rows):
    r = []  
    for y in range(Columns): 
        r.append(int(input()))  
    mat2.append(r)  


for x in range(Rows):  
    for y in range(Columns):  
        print(mat2[x][y], end=" ")  
    print()  


w, v = np.linalg.eig(mat1)

print("Printing the Eigen values of mat1\n", w)
print("Printing Right eigenvectors of mat1\n",v)

w, v = np.linalg.eig(mat2)

print("Printing the Eigen values of mat2\n", w)
print("Printing Right eigenvectors of mat2\n",v)



Give the number of rows:2
Give the number of columns:2
Please give the entries of matrix1 row-wise:
1
2
2
3
1 2 
2 3 
Give the number of rows:2
Give the number of columns:2
Please give the entries of matrix 2 row-wise:
3
4
5
6
3 4 
5 6 
Printing the Eigen values of mat1
 [-0.23606798  4.23606798]
Printing Right eigenvectors of mat1
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]
Printing the Eigen values of mat2
 [-0.21699057  9.21699057]
Printing Right eigenvectors of mat2
 [[-0.77925158 -0.54107946]
 [ 0.62671124 -0.84097147]]
